#!/bin/bash

set -eu -o pipefail
mysqldump db | gzip >/var/www/html/.ddev/.downloads/prod/db_push.sql.gz
rsync -avz /var/www/html/.ddev/.downloads/prod/db_push.sql.gz "${SSH_USERNAME}@{$SERVER_URL}:/tmp/afwd10/prod/db.sql.gz"
