#!/bin/bash

set -eu -o pipefail
pushd /var/www/html/.ddev/.downloads/prod >/dev/null
rm -f files.tar.gz
rsync -avz "${SSH_USERNAME}@{$SERVER_URL}:/tmp/afwd10/prod/files.tar.gz" .
tar -xzf files.tar.gz -C files/
